package com.example.myapplication.model;

/**
 * Domain Model Entity representing a compiled physical workout session.
 * This POJO (Plain Old Java Object) serves as the declarative schema contract for
 * cloud serialization and mapping within Google Cloud Firestore.
 * * Serialization Design: Holds immutable primitive attributes representing both raw data aggregates
 * and analytical outputs generated by the analytics sub-systems.
 */
public class Workout {

    private long timestamp;
    private int totalSteps;
    private int cadence;
    private int pitch;

    public Workout(long timestamp, int totalSteps, int cadence, int pitch) {
        this.timestamp = timestamp;
        this.totalSteps = totalSteps;
        this.cadence = cadence;
        this.pitch = pitch;
    }


    public long getTimestamp() { return timestamp; }
    public int getTotalSteps() { return totalSteps; }
    public int getCadence() { return cadence; }
    public int getPitch() { return pitch; }
}